import {
  Student,
  Teacher,
  Subject,
  ClassGroup,
  ClassSession,
  Invoice,
  Payment,
  QuickTask,
  NotificationItem,
} from "@/types";

export const MOCK_SUBJECTS: Subject[] = [
  { id: "sub-1", code: "MATH", nameAr: "الرياضيات", nameFr: "Mathématiques", color: "#6366F1", active: true },
  { id: "sub-2", code: "PHYS", nameAr: "العلوم الفيزيائية", nameFr: "Physique-Chimie", color: "#0EA5E9", active: true },
  { id: "sub-3", code: "SCI", nameAr: "علوم الطبيعة والحياة", nameFr: "Sciences Naturelles", color: "#10B981", active: true },
  { id: "sub-4", code: "ENG", nameAr: "اللغة الإنجليزية", nameFr: "Langue Anglaise", color: "#F59E0B", active: true },
  { id: "sub-5", code: "FR", nameAr: "اللغة الفرنسية", nameFr: "Langue Française", color: "#EC4899", active: true },
  { id: "sub-6", code: "ARA", nameAr: "اللغة العربية وآدابها", nameFr: "Langue Arabe", color: "#8B5CF6", active: true },
  { id: "sub-7", code: "PHIL", nameAr: "الفلسفة", nameFr: "Philosophie", color: "#14B8A6", active: true },
];

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: "t-1",
    fullName: "أ. عبد القادر بوعلام",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    phone: "0550 12 34 56",
    email: "a.boualem@madrasatipro.dz",
    subjects: ["الرياضيات"],
    groupsCount: 6,
    studentsCount: 104,
    hourlyRate: 2000,
    salaryType: "hourly",
    completedHoursThisMonth: 38,
    totalDueThisMonth: 76000,
    totalPaidThisMonth: 50000,
    balanceThisMonth: 26000,
    status: "active",
    todayClassesCount: 3,
  },
  {
    id: "t-2",
    fullName: "أ. سميرة بن عيسى",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    phone: "0661 98 76 54",
    email: "s.benaissa@madrasatipro.dz",
    subjects: ["العلوم الفيزيائية"],
    groupsCount: 4,
    studentsCount: 78,
    hourlyRate: 1800,
    salaryType: "hourly",
    completedHoursThisMonth: 32,
    totalDueThisMonth: 57600,
    totalPaidThisMonth: 40000,
    balanceThisMonth: 17600,
    status: "active",
    todayClassesCount: 2,
  },
  {
    id: "t-3",
    fullName: "أ. طارق مزيان",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    phone: "0770 45 67 89",
    email: "t.meziane@madrasatipro.dz",
    subjects: ["علوم الطبيعة والحياة"],
    groupsCount: 5,
    studentsCount: 92,
    hourlyRate: 1900,
    salaryType: "hourly",
    completedHoursThisMonth: 30,
    totalDueThisMonth: 57000,
    totalPaidThisMonth: 57000,
    balanceThisMonth: 0,
    status: "active",
    todayClassesCount: 2,
  },
  {
    id: "t-4",
    fullName: "أ. فاطمة الزهراء قاسمي",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    phone: "0555 77 88 99",
    email: "fz.kacimi@madrasatipro.dz",
    subjects: ["اللغة الإنجليزية"],
    groupsCount: 4,
    studentsCount: 65,
    hourlyRate: 1600,
    salaryType: "hourly",
    completedHoursThisMonth: 28,
    totalDueThisMonth: 44800,
    totalPaidThisMonth: 30000,
    balanceThisMonth: 14800,
    status: "active",
    todayClassesCount: 1,
  },
  {
    id: "t-5",
    fullName: "أ. كريم بلحاج",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    phone: "0660 33 22 11",
    email: "k.belhadj@madrasatipro.dz",
    subjects: ["اللغة العربية وآدابها"],
    groupsCount: 3,
    studentsCount: 52,
    hourlyRate: 1500,
    salaryType: "hourly",
    completedHoursThisMonth: 24,
    totalDueThisMonth: 36000,
    totalPaidThisMonth: 25000,
    balanceThisMonth: 11000,
    status: "active",
    todayClassesCount: 1,
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: "stu-1",
    firstName: "محمد أمين",
    lastName: "بلقاسم",
    phone: "0551 23 45 67",
    email: "amine.belkacem@gmail.com",
    gender: "male",
    dateOfBirth: "2008-04-14",
    wilayaCode: 19,
    wilayaName: "سطيف",
    address: "حي الهضاب، سطيف",
    academicLevel: "3AS",
    stream: "علوم تجريبية",
    groupName: "فوج 3AS - رياضيات وتجريبية A",
    groupId: "grp-1",
    parentId: "par-1",
    parentName: "عمر بلقاسم",
    parentPhone: "0661 11 22 33",
    parentRelationship: "الأب",
    enrollmentDate: "2025-09-10",
    status: "active",
    attendanceRate: 95,
    averageGrade: 17.5,
    totalDue: 24000,
    totalPaid: 24000,
    balance: 0,
    monthlyFee: 4000,
  },
  {
    id: "stu-2",
    firstName: "سارة",
    lastName: "بوجمعة",
    phone: "0662 34 56 78",
    email: "sara.boudjemaa@gmail.com",
    gender: "female",
    dateOfBirth: "2008-11-20",
    wilayaCode: 19,
    wilayaName: "سطيف",
    address: "حي 1014 مسكن، سطيف",
    academicLevel: "3AS",
    stream: "رياضيات",
    groupName: "فوج 3AS - رياضيات وتجريبية A",
    groupId: "grp-1",
    parentId: "par-2",
    parentName: "فاروق بوجمعة",
    parentPhone: "0770 99 88 77",
    parentRelationship: "الأب",
    enrollmentDate: "2025-09-12",
    status: "active",
    attendanceRate: 91,
    averageGrade: 18.25,
    totalDue: 24000,
    totalPaid: 16000,
    balance: 8000,
    monthlyFee: 4000,
  },
  {
    id: "stu-3",
    firstName: "ياسين",
    lastName: "حداد",
    phone: "0770 12 98 43",
    gender: "male",
    dateOfBirth: "2009-02-15",
    wilayaCode: 19,
    wilayaName: "سطيف",
    academicLevel: "2AS",
    stream: "علوم تجريبية",
    groupName: "فوج 2AS - فيزياء B",
    groupId: "grp-2",
    parentId: "par-3",
    parentName: "سميحة حداد",
    parentPhone: "0550 44 55 66",
    parentRelationship: "الأم",
    enrollmentDate: "2025-09-15",
    status: "active",
    attendanceRate: 88,
    averageGrade: 15.0,
    totalDue: 20000,
    totalPaid: 20000,
    balance: 0,
    monthlyFee: 3500,
  },
  {
    id: "stu-4",
    firstName: "مريم",
    lastName: "بن علي",
    phone: "0553 45 67 89",
    gender: "female",
    dateOfBirth: "2010-06-08",
    wilayaCode: 19,
    wilayaName: "سطيف",
    academicLevel: "4AM",
    groupName: "فوج 4AM - BEM Blanc تحضير",
    groupId: "grp-3",
    parentId: "par-4",
    parentName: "كمال بن علي",
    parentPhone: "0663 77 66 55",
    parentRelationship: "الأب",
    enrollmentDate: "2025-09-18",
    status: "active",
    attendanceRate: 98,
    averageGrade: 19.1,
    totalDue: 18000,
    totalPaid: 18000,
    balance: 0,
    monthlyFee: 3000,
  },
  {
    id: "stu-5",
    firstName: "إياد",
    lastName: "زروقي",
    phone: "0665 11 22 44",
    gender: "male",
    dateOfBirth: "2008-09-12",
    wilayaCode: 19,
    wilayaName: "سطيف",
    academicLevel: "3AS",
    stream: "تقني رياضي",
    groupName: "فوج 3AS - رياضيات وتجريبية A",
    groupId: "grp-1",
    parentId: "par-5",
    parentName: "حكيم زروقي",
    parentPhone: "0771 22 33 44",
    parentRelationship: "الأب",
    enrollmentDate: "2025-10-01",
    status: "suspended",
    attendanceRate: 72,
    averageGrade: 11.5,
    totalDue: 24000,
    totalPaid: 12000,
    balance: 12000,
    monthlyFee: 4000,
  },
  {
    id: "stu-6",
    firstName: "إكرام",
    lastName: "سلطاني",
    phone: "0554 99 88 11",
    gender: "female",
    dateOfBirth: "2009-08-25",
    wilayaCode: 19,
    wilayaName: "سطيف",
    academicLevel: "2AS",
    stream: "رياضيات",
    groupName: "فوج 2AS - فيزياء B",
    groupId: "grp-2",
    parentId: "par-6",
    parentName: "جمال سلطاني",
    parentPhone: "0664 55 44 33",
    parentRelationship: "الأب",
    enrollmentDate: "2025-09-20",
    status: "active",
    attendanceRate: 94,
    averageGrade: 16.75,
    totalDue: 21000,
    totalPaid: 21000,
    balance: 0,
    monthlyFee: 3500,
  },
  {
    id: "stu-7",
    firstName: "عبد النور",
    lastName: "ميباركي",
    phone: "0772 33 44 55",
    gender: "male",
    dateOfBirth: "2010-01-30",
    wilayaCode: 19,
    wilayaName: "سطيف",
    academicLevel: "4AM",
    groupName: "فوج 4AM - BEM Blanc تحضير",
    groupId: "grp-3",
    parentId: "par-7",
    parentName: "نور الدين ميباركي",
    parentPhone: "0552 11 99 88",
    parentRelationship: "الأب",
    enrollmentDate: "2025-09-14",
    status: "active",
    attendanceRate: 89,
    averageGrade: 14.8,
    totalDue: 18000,
    totalPaid: 12000,
    balance: 6000,
    monthlyFee: 3000,
  },
];

export const MOCK_CLASS_GROUPS: ClassGroup[] = [
  {
    id: "grp-1",
    name: "فوج 3AS - رياضيات وتجريبية A",
    academicLevel: "3AS",
    stream: "علوم تجريبية",
    subjectId: "sub-1",
    subjectName: "الرياضيات",
    subjectColor: "#6366F1",
    teacherId: "t-1",
    teacherName: "أ. عبد القادر بوعلام",
    roomName: "قاعة الخوارزمي (03)",
    studentsCount: 18,
    maxCapacity: 20,
    scheduleDescription: "السبت والثلاثاء 09:00 - 10:30",
    dayOfWeek: 6,
    startTime: "09:00",
    endTime: "10:30",
    monthlyFee: 4000,
  },
  {
    id: "grp-2",
    name: "فوج 2AS - فيزياء B",
    academicLevel: "2AS",
    stream: "علوم تجريبية",
    subjectId: "sub-2",
    subjectName: "العلوم الفيزيائية",
    subjectColor: "#0EA5E9",
    teacherId: "t-2",
    teacherName: "أ. سميرة بن عيسى",
    roomName: "مخبر ابن الهيثم (01)",
    studentsCount: 16,
    maxCapacity: 18,
    scheduleDescription: "الأحد والأربعاء 11:00 - 12:30",
    dayOfWeek: 0,
    startTime: "11:00",
    endTime: "12:30",
    monthlyFee: 3500,
  },
  {
    id: "grp-3",
    name: "فوج 4AM - BEM Blanc تحضير",
    academicLevel: "4AM",
    subjectId: "sub-3",
    subjectName: "علوم الطبيعة والحياة",
    subjectColor: "#10B981",
    teacherId: "t-3",
    teacherName: "أ. طارق مزيان",
    roomName: "قاعة ابن سينا (04)",
    studentsCount: 15,
    maxCapacity: 20,
    scheduleDescription: "السبت 14:00 - 16:00",
    dayOfWeek: 6,
    startTime: "14:00",
    endTime: "16:00",
    monthlyFee: 3000,
  },
  {
    id: "grp-4",
    name: "فوج لغات A1 - إنجليزية مكثفة",
    academicLevel: "LANG_EN_A1",
    subjectId: "sub-4",
    subjectName: "اللغة الإنجليزية",
    subjectColor: "#F59E0B",
    teacherId: "t-4",
    teacherName: "أ. فاطمة الزهراء قاسمي",
    roomName: "قاعة اللغات (02)",
    studentsCount: 12,
    maxCapacity: 15,
    scheduleDescription: "الإثنين والخميس 16:30 - 18:00",
    dayOfWeek: 1,
    startTime: "16:30",
    endTime: "18:00",
    monthlyFee: 4500,
  },
];

export const MOCK_UPCOMING_CLASSES: {
  id: string;
  timeRange: string;
  title: string;
  subject: string;
  group: string;
  room: string;
  teacher: string;
  accentColor: string;
}[] = [
  {
    id: "up-1",
    timeRange: "09:00 - 10:30",
    title: "الرياضيات — المتتاليات وحساب النهايات",
    subject: "الرياضيات",
    group: "3AS علوم تجريبية (فوج A)",
    room: "قاعة الخوارزمي (03)",
    teacher: "أ. عبد القادر بوعلام",
    accentColor: "#6366F1", // Indigo
  },
  {
    id: "up-2",
    timeRange: "11:00 - 12:30",
    title: "الفيزياء — الميكانيك وقوانين نيوتن",
    subject: "العلوم الفيزيائية",
    group: "2AS علوم تجريبية (فوج B)",
    room: "مخبر ابن الهيثم (01)",
    teacher: "أ. سميرة بن عيسى",
    accentColor: "#0EA5E9", // Sky
  },
  {
    id: "up-3",
    timeRange: "14:00 - 15:30",
    title: "علوم الطبيعة — تركيب البروتين والإنزيمات",
    subject: "علوم الطبيعة والحياة",
    group: "فوج 4AM (تحضير BEM)",
    room: "قاعة ابن سينا (04)",
    teacher: "أ. طارق مزيان",
    accentColor: "#10B981", // Emerald
  },
  {
    id: "up-4",
    timeRange: "16:00 - 17:30",
    title: "اللغة الإنجليزية — IELTS Speaking & Writing",
    subject: "اللغة الإنجليزية",
    group: "فوج تكوين اللغات (A1)",
    room: "قاعة اللغات (02)",
    teacher: "أ. فاطمة الزهراء قاسمي",
    accentColor: "#F59E0B", // Amber
  },
  {
    id: "up-5",
    timeRange: "18:00 - 19:30",
    title: "الفلسفة — إشكالية المشكلة والإشكالية",
    subject: "الفلسفة",
    group: "3AS آداب وفلسفة",
    room: "قاعة الفارابي (05)",
    teacher: "أ. كريم بلحاج",
    accentColor: "#EC4899", // Rose
  },
];

export const MOCK_QUICK_TASKS: QuickTask[] = [
  {
    id: "task-1",
    title: "فرض الفصل الثاني — الرياضيات 3AS",
    category: "الرياضيات • 3AS علوم",
    timeframe: "غداً في 09:00",
    iconType: "pen",
    urgent: true,
  },
  {
    id: "task-2",
    title: "تحصيل أقساط فوج البكالوريا — 4 طلاب",
    category: "مستحقات متأخرة: 86,000 دج",
    timeframe: "خلال 48 ساعة",
    iconType: "book",
    urgent: false,
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n-1",
    title: "تسجيل غياب طالب",
    message: "تم تسجيل غياب محمد أمين بلقاسم في حصة الرياضيات 09:00 مع إشعار الولي.",
    time: "منذ 15 دقيقة",
    type: "attendance",
    isRead: false,
  },
  {
    id: "n-2",
    title: "دفعة جديدة مؤكدة",
    message: "قام الولي كمال بن علي بدفع قسط شهر فيفري (3,000 دج) عبر تطبيق بريدي موب.",
    time: "منذ ساعة",
    type: "payment",
    isRead: false,
  },
  {
    id: "n-3",
    title: "تذكير بالامتحان التجريبي",
    message: "امتحان BAC Blanc فيزياء مجدول يوم السبت القادم على الساعة 08:30.",
    time: "منذ 3 ساعات",
    type: "exam",
    isRead: true,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv-2026-001",
    invoiceNumber: "FC-2026/0189",
    studentId: "stu-1",
    studentName: "محمد أمين بلقاسم",
    parentId: "par-1",
    parentName: "عمر بلقاسم",
    issueDate: "2026-02-01",
    dueDate: "2026-02-10",
    items: [
      { id: "item-1", description: "اشتراك شهري — رياضيات 3AS (8 حصص)", amount: 4000 },
      { id: "item-2", description: "مطبوعات وتمارين البكالوريا النموذجية", amount: 500 },
    ],
    subtotal: 4500,
    discountTotal: 0,
    finalTotal: 4500,
    amountPaid: 4500,
    remainingBalance: 0,
    status: "paid",
    academicCycle: "التعليم الثانوي — 3AS",
  },
  {
    id: "inv-2026-002",
    invoiceNumber: "FC-2026/0190",
    studentId: "stu-2",
    studentName: "سارة بوجمعة",
    parentId: "par-2",
    parentName: "فاروق بوجمعة",
    issueDate: "2026-02-01",
    dueDate: "2026-02-10",
    items: [
      { id: "item-3", description: "اشتراك شهري — رياضيات وفيزياء 3AS", amount: 7500 },
      { id: "item-4", description: "خصم التميز الدراسي", amount: -1000 },
    ],
    subtotal: 7500,
    discountTotal: 1000,
    finalTotal: 6500,
    amountPaid: 3500,
    remainingBalance: 3000,
    status: "partially_paid",
    academicCycle: "التعليم الثانوي — 3AS",
  },
  {
    id: "inv-2026-003",
    invoiceNumber: "FC-2026/0191",
    studentId: "stu-5",
    studentName: "إياد زروقي",
    parentId: "par-5",
    parentName: "حكيم زروقي",
    issueDate: "2026-01-15",
    dueDate: "2026-01-25",
    items: [
      { id: "item-5", description: "اشتراك شهر جانفي وفيفري — رياضيات", amount: 8000 },
    ],
    subtotal: 8000,
    discountTotal: 0,
    finalTotal: 8000,
    amountPaid: 0,
    remainingBalance: 8000,
    status: "overdue",
    academicCycle: "التعليم الثانوي — 3AS",
  },
];
